//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerM
    {
        public int Custid { get; set; }
        public string CustCountry { get; set; }
        public string ROCID { get; set; }
        public string PASSPOART_CODE { get; set; }
        public string PASSPOART_NO { get; set; }
        public string Sex { get; set; }
        public string CustNameLocal { get; set; }
        public string CustNameEn { get; set; }
    }
}
