//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerD
    {
        public int Custid { get; set; }
        public string PhoneHomeAreaCode { get; set; }
        public string PhoneHome { get; set; }
        public string PhoneHomeExt { get; set; }
        public string PhoneCorpAreaCode { get; set; }
        public string PhoneCorp { get; set; }
        public string PhoneCorpExt { get; set; }
        public string PhoneMobileATW { get; set; }
        public string AddressPermanent { get; set; }
        public string AddressPermanentZipcode { get; set; }
        public string AddressCorrespondence { get; set; }
        public string AddressCorrespondenceZipcode { get; set; }
        public string Email { get; set; }
    
        public virtual CustomerD CustomerD1 { get; set; }
        public virtual CustomerD CustomerD2 { get; set; }
    }
}
