//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceSys.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CustomerD> CustomerD { get; set; }
        public virtual DbSet<CustomerM> CustomerM { get; set; }
        public virtual DbSet<SysCode> SysCode { get; set; }
        public virtual DbSet<UserInfoM> UserInfoM { get; set; }

        public System.Data.Entity.DbSet<InsuranceSys.Models.ViewModels.CustomerViewModel> CustomerViewModels { get; set; }
    }
}
